### PR TITLE
Bug Fixes: SDFG Breakpoints Debug Panel

### PR DESCRIPTION
**Pull request by benibenj**
- Fixed: Jump to SDFG from SDFG Breakpoints sometimes didn't open the viewer
- If an SDFG Breakpoint is removed. The parent div shouldn't trigger a click event

### CODE REVIEW

**Review by tbennun — APPROVED** [review]
Not sure about the `if ($(e.target).is('.remove-bp')) return` part, seems like it's not general enough.

I'll let @phschaad have the final word.

**Comment by benibenj** [comment]
I found a better solution: ```event.stopPropagation();```. This makes sure that the click event on the child element doesn't propagate to a click on the parent element.

**Comment by tbennun** [comment]
@benibenj that's exactly the solution I was waiting for (I also think you can return false from that callback?)

**Comment by benibenj** [comment]
You're right. Returning false stops propagation and the default behaviour (which a div does not have).

**Comment by phschaad** [comment]
The `return false` method looks good to me - this works.

**Pull request merged**
